# Generated by Django 5.1.3 on 2024-11-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user',), name='unique_pending_order_per_user'),
        ),
    ]
